export const COLORS = {
  light: {
    "--primary-color": "#1da1f2",
    "--text-color": "#14171a",
    "--dark-gray": "#657786",
    "--light-gray": "#aab8c2",
    "--hover": "#e1e8ed",
    "--background": "#f5f8fa",
    "--card": "#fff",
    "--white": "#fff",
    "--like": "#e31b23",
    "--danger": "#dc0000",
    "--light-danger": "#fedada",
    "--hover-danger": "#feb1b1",
  },
  dark: {
    "--primary-color": "#1da1f2",
    "--text-color": "#ffffff",
    "--dark-gray": "#8899a6",
    "--light-gray": "#aab8c2",
    "--hover": "#22303c",
    "--background": "#15202b",
    "--card": "#192734",
    "--white": "#ffffff",
    "--like": "#e31b23",
    "--danger": "#dc0000",
    "--light-danger": "#fedada",
    "--hover-danger": "#feb1b1",
  },
};
